services:
  postgres:
    image: postgres:16-alpine
    container_name: campus_motion_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - epfl_private_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5432:5432

  api-server:
    build:
      context: ./api_v1
      dockerfile: Dockerfile
    container_name: campus_motion_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      API_DB_URL: ${API_DB_URL}
      AUTH_DB_URL: ${AUTH_DB_URL}
      ADMIN_DB_URL: ${ADMIN_DB_URL}
      AUDIT_DB_URL: ${AUDIT_DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    networks:
      - epfl_private_network
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
      - uploads_data:/app/uploads/news
      - uploads_data:/app/uploads/events
      - uploads_data:/app/uploads/profiles

networks:
  epfl_private_network:
    driver: bridge

volumes:
  pgdata:
  uploads_data:
